// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs3GRZrPTF530F3KDwImzOFfrZ8A30SQ8',
    appId: '1:651870655421:web:bcddf5f0b3180c1c31f8d4',
    messagingSenderId: '651870655421',
    projectId: 'tadreebkom',
    authDomain: 'tadreebkom.firebaseapp.com',
    storageBucket: 'tadreebkom.firebasestorage.app',
    measurementId: 'G-N0R1V6E1TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjPecczDvxR2yHcNULGcU0cNidCwsd9Pc',
    appId: '1:651870655421:android:caaf0e41eeca5a1831f8d4',
    messagingSenderId: '651870655421',
    projectId: 'tadreebkom',
    storageBucket: 'tadreebkom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyypNo4h3-KUyB_Zy3MqWGGTvIdHtaeBI',
    appId: '1:651870655421:ios:930704c3e132024031f8d4',
    messagingSenderId: '651870655421',
    projectId: 'tadreebkom',
    storageBucket: 'tadreebkom.firebasestorage.app',
    androidClientId: '651870655421-618scu8robt9actpplj65eve75h6ahbk.apps.googleusercontent.com',
    iosClientId: '651870655421-0d2m5m8r9q6p0qe1oa8s2bjhuvtp85e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tadreebkomapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyypNo4h3-KUyB_Zy3MqWGGTvIdHtaeBI',
    appId: '1:651870655421:ios:930704c3e132024031f8d4',
    messagingSenderId: '651870655421',
    projectId: 'tadreebkom',
    storageBucket: 'tadreebkom.firebasestorage.app',
    androidClientId: '651870655421-618scu8robt9actpplj65eve75h6ahbk.apps.googleusercontent.com',
    iosClientId: '651870655421-0d2m5m8r9q6p0qe1oa8s2bjhuvtp85e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tadreebkomapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs3GRZrPTF530F3KDwImzOFfrZ8A30SQ8',
    appId: '1:651870655421:web:238625bd8e1ac2df31f8d4',
    messagingSenderId: '651870655421',
    projectId: 'tadreebkom',
    authDomain: 'tadreebkom.firebaseapp.com',
    storageBucket: 'tadreebkom.firebasestorage.app',
    measurementId: 'G-4JYVQFBQ0Z',
  );

}